package com.quwb.web.entity;

public class BusinessType {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BusinessType.BusinessID
     *
     * @mbg.generated
     */
    private Integer businessid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BusinessType.BusinessDes
     *
     * @mbg.generated
     */
    private String businessdes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BusinessType.SortNum
     *
     * @mbg.generated
     */
    private Short sortnum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BusinessType.IsShow
     *
     * @mbg.generated
     */
    private Short isshow;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BusinessType.Icon
     *
     * @mbg.generated
     */
    private String icon;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BusinessType.LargeIcon
     *
     * @mbg.generated
     */
    private String largeicon;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BusinessType.BusinessID
     *
     * @return the value of BusinessType.BusinessID
     *
     * @mbg.generated
     */
    public Integer getBusinessid() {
        return businessid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BusinessType.BusinessID
     *
     * @param businessid the value for BusinessType.BusinessID
     *
     * @mbg.generated
     */
    public void setBusinessid(Integer businessid) {
        this.businessid = businessid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BusinessType.BusinessDes
     *
     * @return the value of BusinessType.BusinessDes
     *
     * @mbg.generated
     */
    public String getBusinessdes() {
        return businessdes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BusinessType.BusinessDes
     *
     * @param businessdes the value for BusinessType.BusinessDes
     *
     * @mbg.generated
     */
    public void setBusinessdes(String businessdes) {
        this.businessdes = businessdes == null ? null : businessdes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BusinessType.SortNum
     *
     * @return the value of BusinessType.SortNum
     *
     * @mbg.generated
     */
    public Short getSortnum() {
        return sortnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BusinessType.SortNum
     *
     * @param sortnum the value for BusinessType.SortNum
     *
     * @mbg.generated
     */
    public void setSortnum(Short sortnum) {
        this.sortnum = sortnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BusinessType.IsShow
     *
     * @return the value of BusinessType.IsShow
     *
     * @mbg.generated
     */
    public Short getIsshow() {
        return isshow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BusinessType.IsShow
     *
     * @param isshow the value for BusinessType.IsShow
     *
     * @mbg.generated
     */
    public void setIsshow(Short isshow) {
        this.isshow = isshow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BusinessType.Icon
     *
     * @return the value of BusinessType.Icon
     *
     * @mbg.generated
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BusinessType.Icon
     *
     * @param icon the value for BusinessType.Icon
     *
     * @mbg.generated
     */
    public void setIcon(String icon) {
        this.icon = icon == null ? null : icon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BusinessType.LargeIcon
     *
     * @return the value of BusinessType.LargeIcon
     *
     * @mbg.generated
     */
    public String getLargeicon() {
        return largeicon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BusinessType.LargeIcon
     *
     * @param largeicon the value for BusinessType.LargeIcon
     *
     * @mbg.generated
     */
    public void setLargeicon(String largeicon) {
        this.largeicon = largeicon == null ? null : largeicon.trim();
    }
}