package com.quwb.web.entity;

import com.quwb.web.common.CustomJsonDateDeserializer;
import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;

import java.util.Date;

public class MsgInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MsgInfo.MsgID
     *
     * @mbg.generated
     */
    private Integer msgid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MsgInfo.Mobile
     *
     * @mbg.generated
     */
    private String mobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MsgInfo.MsgContent
     *
     * @mbg.generated
     */
    private String msgcontent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MsgInfo.MsgIP
     *
     * @mbg.generated
     */
    private String msgip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MsgInfo.SendStatus
     *
     * @mbg.generated
     */
    private Short sendstatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MsgInfo.SendTime
     *
     * @mbg.generated
     */
    @JsonFormat(timezone = "GMT+8", pattern = "yyyy-MM-dd HH:mm:ss")
    private Date sendtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MsgInfo.SourceID
     *
     * @mbg.generated
     */
    private Integer sourceid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MsgInfo.CreateTime
     *
     * @mbg.generated
     */
    @JsonFormat(timezone = "GMT+8", pattern = "yyyy-MM-dd HH:mm:ss")
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MsgInfo.IsActive
     *
     * @mbg.generated
     */
    private Short isactive;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MsgInfo.MsgID
     *
     * @return the value of MsgInfo.MsgID
     *
     * @mbg.generated
     */
    public Integer getMsgid() {
        return msgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MsgInfo.MsgID
     *
     * @param msgid the value for MsgInfo.MsgID
     *
     * @mbg.generated
     */
    public void setMsgid(Integer msgid) {
        this.msgid = msgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MsgInfo.Mobile
     *
     * @return the value of MsgInfo.Mobile
     *
     * @mbg.generated
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MsgInfo.Mobile
     *
     * @param mobile the value for MsgInfo.Mobile
     *
     * @mbg.generated
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MsgInfo.MsgContent
     *
     * @return the value of MsgInfo.MsgContent
     *
     * @mbg.generated
     */
    public String getMsgcontent() {
        return msgcontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MsgInfo.MsgContent
     *
     * @param msgcontent the value for MsgInfo.MsgContent
     *
     * @mbg.generated
     */
    public void setMsgcontent(String msgcontent) {
        this.msgcontent = msgcontent == null ? null : msgcontent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MsgInfo.MsgIP
     *
     * @return the value of MsgInfo.MsgIP
     *
     * @mbg.generated
     */
    public String getMsgip() {
        return msgip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MsgInfo.MsgIP
     *
     * @param msgip the value for MsgInfo.MsgIP
     *
     * @mbg.generated
     */
    public void setMsgip(String msgip) {
        this.msgip = msgip == null ? null : msgip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MsgInfo.SendStatus
     *
     * @return the value of MsgInfo.SendStatus
     *
     * @mbg.generated
     */
    public Short getSendstatus() {
        return sendstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MsgInfo.SendStatus
     *
     * @param sendstatus the value for MsgInfo.SendStatus
     *
     * @mbg.generated
     */
    public void setSendstatus(Short sendstatus) {
        this.sendstatus = sendstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MsgInfo.SendTime
     *
     * @return the value of MsgInfo.SendTime
     *
     * @mbg.generated
     */
    public Date getSendtime() {
        return sendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MsgInfo.SendTime
     *
     * @param sendtime the value for MsgInfo.SendTime
     *
     * @mbg.generated
     */
    //@JsonDeserialize(using = CustomJsonDateDeserializer.class)
    public void setSendtime(Date sendtime) {
        this.sendtime = sendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MsgInfo.SourceID
     *
     * @return the value of MsgInfo.SourceID
     *
     * @mbg.generated
     */
    public Integer getSourceid() {
        return sourceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MsgInfo.SourceID
     *
     * @param sourceid the value for MsgInfo.SourceID
     *
     * @mbg.generated
     */
    public void setSourceid(Integer sourceid) {
        this.sourceid = sourceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MsgInfo.CreateTime
     *
     * @return the value of MsgInfo.CreateTime
     *
     * @mbg.generated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MsgInfo.CreateTime
     *
     * @param createtime the value for MsgInfo.CreateTime
     *
     * @mbg.generated
     */
    //@JsonDeserialize(using = CustomJsonDateDeserializer.class)
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MsgInfo.IsActive
     *
     * @return the value of MsgInfo.IsActive
     *
     * @mbg.generated
     */
    public Short getIsactive() {
        return isactive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MsgInfo.IsActive
     *
     * @param isactive the value for MsgInfo.IsActive
     *
     * @mbg.generated
     */
    public void setIsactive(Short isactive) {
        this.isactive = isactive;
    }
}