package com.quwb.web.entity;

import com.fasterxml.jackson.annotation.JsonFormat;

import java.util.Date;

public class PublisherInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PublisherInfo.ShopID
     *
     * @mbg.generated
     */
    private Long shopid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PublisherInfo.UserName
     *
     * @mbg.generated
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PublisherInfo.UserMobile
     *
     * @mbg.generated
     */
    private String usermobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PublisherInfo.MobilePic
     *
     * @mbg.generated
     */
    private String mobilepic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PublisherInfo.CreateTime
     *
     * @mbg.generated
     */
    @JsonFormat(timezone = "GMT+8", pattern = "yyyy-MM-dd HH:mm:ss")
    private Date createtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PublisherInfo.ShopID
     *
     * @return the value of PublisherInfo.ShopID
     *
     * @mbg.generated
     */
    public Long getShopid() {
        return shopid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PublisherInfo.ShopID
     *
     * @param shopid the value for PublisherInfo.ShopID
     *
     * @mbg.generated
     */
    public void setShopid(Long shopid) {
        this.shopid = shopid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PublisherInfo.UserName
     *
     * @return the value of PublisherInfo.UserName
     *
     * @mbg.generated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PublisherInfo.UserName
     *
     * @param username the value for PublisherInfo.UserName
     *
     * @mbg.generated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PublisherInfo.UserMobile
     *
     * @return the value of PublisherInfo.UserMobile
     *
     * @mbg.generated
     */
    public String getUsermobile() {
        return usermobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PublisherInfo.UserMobile
     *
     * @param usermobile the value for PublisherInfo.UserMobile
     *
     * @mbg.generated
     */
    public void setUsermobile(String usermobile) {
        this.usermobile = usermobile == null ? null : usermobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PublisherInfo.MobilePic
     *
     * @return the value of PublisherInfo.MobilePic
     *
     * @mbg.generated
     */
    public String getMobilepic() {
        return mobilepic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PublisherInfo.MobilePic
     *
     * @param mobilepic the value for PublisherInfo.MobilePic
     *
     * @mbg.generated
     */
    public void setMobilepic(String mobilepic) {
        this.mobilepic = mobilepic == null ? null : mobilepic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PublisherInfo.CreateTime
     *
     * @return the value of PublisherInfo.CreateTime
     *
     * @mbg.generated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PublisherInfo.CreateTime
     *
     * @param createtime the value for PublisherInfo.CreateTime
     *
     * @mbg.generated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }
}