package com.quwb.web.entity;

import com.fasterxml.jackson.annotation.JsonFormat;

import java.util.Date;

public class ShopInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ShopInfo.ShopID
     *
     * @mbg.generated
     */
    private Long shopid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ShopInfo.ShopTilte
     *
     * @mbg.generated
     */
    private String shoptilte;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ShopInfo.ShopPrice
     *
     * @mbg.generated
     */
    private Double shopprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ShopInfo.ShopArea
     *
     * @mbg.generated
     */
    private Integer shoparea;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ShopInfo.ShopDisc
     *
     * @mbg.generated
     */
    private String shopdisc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ShopInfo.BusinessID
     *
     * @mbg.generated
     */
    private Integer businessid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ShopInfo.CityName
     *
     * @mbg.generated
     */
    private String cityname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ShopInfo.AreaName
     *
     * @mbg.generated
     */
    private String areaname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ShopInfo.BurgName
     *
     * @mbg.generated
     */
    private String burgname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ShopInfo.SourceID
     *
     * @mbg.generated
     */
    private Integer sourceid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ShopInfo.PublishTime
     *
     * @mbg.generated
     */
    @JsonFormat(timezone = "GMT+8", pattern = "yyyy-MM-dd HH:mm:ss")
    private Date publishtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ShopInfo.ModifyStatus
     *
     * @mbg.generated
     */
    private Short modifystatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ShopInfo.HouseIndustry
     *
     * @mbg.generated
     */
    private String houseindustry;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ShopInfo.HousePriceUnit
     *
     * @mbg.generated
     */
    private String housepriceunit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ShopInfo.TransFee
     *
     * @mbg.generated
     */
    private String transfee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ShopInfo.Address
     *
     * @mbg.generated
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ShopInfo.CreateTime
     *
     * @mbg.generated
     */
    @JsonFormat(timezone = "GMT+8", pattern = "yyyy-MM-dd HH:mm:ss")
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ShopInfo.UpdateTime
     *
     * @mbg.generated
     */
    @JsonFormat(timezone = "GMT+8", pattern = "yyyy-MM-dd HH:mm:ss")
    private Date updatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ShopInfo.IsActive
     *
     * @mbg.generated
     */
    private Short isactive;

    private PublisherInfo publisherInfo;

    public PublisherInfo getPublisherInfo(){ return this.publisherInfo; }
    public void setPublisherInfo(PublisherInfo publisherInfo){ this.publisherInfo = publisherInfo; }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ShopInfo.ShopID
     *
     * @return the value of ShopInfo.ShopID
     *
     * @mbg.generated
     */
    public Long getShopid() {
        return shopid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ShopInfo.ShopID
     *
     * @param shopid the value for ShopInfo.ShopID
     *
     * @mbg.generated
     */
    public void setShopid(Long shopid) {
        this.shopid = shopid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ShopInfo.ShopTilte
     *
     * @return the value of ShopInfo.ShopTilte
     *
     * @mbg.generated
     */
    public String getShoptilte() {
        return shoptilte;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ShopInfo.ShopTilte
     *
     * @param shoptilte the value for ShopInfo.ShopTilte
     *
     * @mbg.generated
     */
    public void setShoptilte(String shoptilte) {
        this.shoptilte = shoptilte == null ? null : shoptilte.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ShopInfo.ShopPrice
     *
     * @return the value of ShopInfo.ShopPrice
     *
     * @mbg.generated
     */
    public Double getShopprice() {
        return shopprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ShopInfo.ShopPrice
     *
     * @param shopprice the value for ShopInfo.ShopPrice
     *
     * @mbg.generated
     */
    public void setShopprice(Double shopprice) {
        this.shopprice = shopprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ShopInfo.ShopArea
     *
     * @return the value of ShopInfo.ShopArea
     *
     * @mbg.generated
     */
    public Integer getShoparea() {
        return shoparea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ShopInfo.ShopArea
     *
     * @param shoparea the value for ShopInfo.ShopArea
     *
     * @mbg.generated
     */
    public void setShoparea(Integer shoparea) {
        this.shoparea = shoparea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ShopInfo.ShopDisc
     *
     * @return the value of ShopInfo.ShopDisc
     *
     * @mbg.generated
     */
    public String getShopdisc() {
        return shopdisc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ShopInfo.ShopDisc
     *
     * @param shopdisc the value for ShopInfo.ShopDisc
     *
     * @mbg.generated
     */
    public void setShopdisc(String shopdisc) {
        this.shopdisc = shopdisc == null ? null : shopdisc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ShopInfo.BusinessID
     *
     * @return the value of ShopInfo.BusinessID
     *
     * @mbg.generated
     */
    public Integer getBusinessid() {
        return businessid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ShopInfo.BusinessID
     *
     * @param businessid the value for ShopInfo.BusinessID
     *
     * @mbg.generated
     */
    public void setBusinessid(Integer businessid) {
        this.businessid = businessid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ShopInfo.CityName
     *
     * @return the value of ShopInfo.CityName
     *
     * @mbg.generated
     */
    public String getCityname() {
        return cityname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ShopInfo.CityName
     *
     * @param cityname the value for ShopInfo.CityName
     *
     * @mbg.generated
     */
    public void setCityname(String cityname) {
        this.cityname = cityname == null ? null : cityname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ShopInfo.AreaName
     *
     * @return the value of ShopInfo.AreaName
     *
     * @mbg.generated
     */
    public String getAreaname() {
        return areaname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ShopInfo.AreaName
     *
     * @param areaname the value for ShopInfo.AreaName
     *
     * @mbg.generated
     */
    public void setAreaname(String areaname) {
        this.areaname = areaname == null ? null : areaname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ShopInfo.BurgName
     *
     * @return the value of ShopInfo.BurgName
     *
     * @mbg.generated
     */
    public String getBurgname() {
        return burgname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ShopInfo.BurgName
     *
     * @param burgname the value for ShopInfo.BurgName
     *
     * @mbg.generated
     */
    public void setBurgname(String burgname) {
        this.burgname = burgname == null ? null : burgname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ShopInfo.SourceID
     *
     * @return the value of ShopInfo.SourceID
     *
     * @mbg.generated
     */
    public Integer getSourceid() {
        return sourceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ShopInfo.SourceID
     *
     * @param sourceid the value for ShopInfo.SourceID
     *
     * @mbg.generated
     */
    public void setSourceid(Integer sourceid) {
        this.sourceid = sourceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ShopInfo.PublishTime
     *
     * @return the value of ShopInfo.PublishTime
     *
     * @mbg.generated
     */
    public Date getPublishtime() {
        return publishtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ShopInfo.PublishTime
     *
     * @param publishtime the value for ShopInfo.PublishTime
     *
     * @mbg.generated
     */
    public void setPublishtime(Date publishtime) {
        this.publishtime = publishtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ShopInfo.ModifyStatus
     *
     * @return the value of ShopInfo.ModifyStatus
     *
     * @mbg.generated
     */
    public Short getModifystatus() {
        return modifystatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ShopInfo.ModifyStatus
     *
     * @param modifystatus the value for ShopInfo.ModifyStatus
     *
     * @mbg.generated
     */
    public void setModifystatus(Short modifystatus) {
        this.modifystatus = modifystatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ShopInfo.HouseIndustry
     *
     * @return the value of ShopInfo.HouseIndustry
     *
     * @mbg.generated
     */
    public String getHouseindustry() {
        return houseindustry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ShopInfo.HouseIndustry
     *
     * @param houseindustry the value for ShopInfo.HouseIndustry
     *
     * @mbg.generated
     */
    public void setHouseindustry(String houseindustry) {
        this.houseindustry = houseindustry == null ? null : houseindustry.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ShopInfo.HousePriceUnit
     *
     * @return the value of ShopInfo.HousePriceUnit
     *
     * @mbg.generated
     */
    public String getHousepriceunit() {
        return housepriceunit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ShopInfo.HousePriceUnit
     *
     * @param housepriceunit the value for ShopInfo.HousePriceUnit
     *
     * @mbg.generated
     */
    public void setHousepriceunit(String housepriceunit) {
        this.housepriceunit = housepriceunit == null ? null : housepriceunit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ShopInfo.TransFee
     *
     * @return the value of ShopInfo.TransFee
     *
     * @mbg.generated
     */
    public String getTransfee() {
        return transfee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ShopInfo.TransFee
     *
     * @param transfee the value for ShopInfo.TransFee
     *
     * @mbg.generated
     */
    public void setTransfee(String transfee) {
        this.transfee = transfee == null ? null : transfee.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ShopInfo.Address
     *
     * @return the value of ShopInfo.Address
     *
     * @mbg.generated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ShopInfo.Address
     *
     * @param address the value for ShopInfo.Address
     *
     * @mbg.generated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ShopInfo.CreateTime
     *
     * @return the value of ShopInfo.CreateTime
     *
     * @mbg.generated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ShopInfo.CreateTime
     *
     * @param createtime the value for ShopInfo.CreateTime
     *
     * @mbg.generated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ShopInfo.UpdateTime
     *
     * @return the value of ShopInfo.UpdateTime
     *
     * @mbg.generated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ShopInfo.UpdateTime
     *
     * @param updatetime the value for ShopInfo.UpdateTime
     *
     * @mbg.generated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ShopInfo.IsActive
     *
     * @return the value of ShopInfo.IsActive
     *
     * @mbg.generated
     */
    public Short getIsactive() {
        return isactive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ShopInfo.IsActive
     *
     * @param isactive the value for ShopInfo.IsActive
     *
     * @mbg.generated
     */
    public void setIsactive(Short isactive) {
        this.isactive = isactive;
    }
}