package com.quwb.web.entity;

import com.fasterxml.jackson.annotation.JsonFormat;

import java.util.Date;

public class ShopDetail {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ShopDetail.DetailID
     *
     * @mbg.generated
     */
    private Long detailid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ShopDetail.ShopID
     *
     * @mbg.generated
     */
    private Long shopid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ShopDetail.Info
     *
     * @mbg.generated
     */
    private String info;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ShopDetail.CreateTime
     *
     * @mbg.generated
     */
    @JsonFormat(timezone = "GMT+8", pattern = "yyyy-MM-dd HH:mm:ss")
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ShopDetail.IsActive
     *
     * @mbg.generated
     */
    private Short isactive;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ShopDetail.DetailID
     *
     * @return the value of ShopDetail.DetailID
     *
     * @mbg.generated
     */
    public Long getDetailid() {
        return detailid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ShopDetail.DetailID
     *
     * @param detailid the value for ShopDetail.DetailID
     *
     * @mbg.generated
     */
    public void setDetailid(Long detailid) {
        this.detailid = detailid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ShopDetail.ShopID
     *
     * @return the value of ShopDetail.ShopID
     *
     * @mbg.generated
     */
    public Long getShopid() {
        return shopid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ShopDetail.ShopID
     *
     * @param shopid the value for ShopDetail.ShopID
     *
     * @mbg.generated
     */
    public void setShopid(Long shopid) {
        this.shopid = shopid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ShopDetail.Info
     *
     * @return the value of ShopDetail.Info
     *
     * @mbg.generated
     */
    public String getInfo() {
        return info;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ShopDetail.Info
     *
     * @param info the value for ShopDetail.Info
     *
     * @mbg.generated
     */
    public void setInfo(String info) {
        this.info = info == null ? null : info.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ShopDetail.CreateTime
     *
     * @return the value of ShopDetail.CreateTime
     *
     * @mbg.generated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ShopDetail.CreateTime
     *
     * @param createtime the value for ShopDetail.CreateTime
     *
     * @mbg.generated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ShopDetail.IsActive
     *
     * @return the value of ShopDetail.IsActive
     *
     * @mbg.generated
     */
    public Short getIsactive() {
        return isactive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ShopDetail.IsActive
     *
     * @param isactive the value for ShopDetail.IsActive
     *
     * @mbg.generated
     */
    public void setIsactive(Short isactive) {
        this.isactive = isactive;
    }
}