package com.quwb.web.entity;

import com.fasterxml.jackson.annotation.JsonFormat;

import java.util.Date;

public class ShopPic {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ShopPic.PicID
     *
     * @mbg.generated
     */
    private Long picid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ShopPic.ShopID
     *
     * @mbg.generated
     */
    private Long shopid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ShopPic.PicUrl
     *
     * @mbg.generated
     */
    private String picurl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ShopPic.CreateTime
     *
     * @mbg.generated
     */
    @JsonFormat(timezone = "GMT+8", pattern = "yyyy-MM-dd HH:mm:ss")
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ShopPic.IsActive
     *
     * @mbg.generated
     */
    private Short isactive;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ShopPic.PicID
     *
     * @return the value of ShopPic.PicID
     *
     * @mbg.generated
     */
    public Long getPicid() {
        return picid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ShopPic.PicID
     *
     * @param picid the value for ShopPic.PicID
     *
     * @mbg.generated
     */
    public void setPicid(Long picid) {
        this.picid = picid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ShopPic.ShopID
     *
     * @return the value of ShopPic.ShopID
     *
     * @mbg.generated
     */
    public Long getShopid() {
        return shopid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ShopPic.ShopID
     *
     * @param shopid the value for ShopPic.ShopID
     *
     * @mbg.generated
     */
    public void setShopid(Long shopid) {
        this.shopid = shopid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ShopPic.PicUrl
     *
     * @return the value of ShopPic.PicUrl
     *
     * @mbg.generated
     */
    public String getPicurl() {
        return picurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ShopPic.PicUrl
     *
     * @param picurl the value for ShopPic.PicUrl
     *
     * @mbg.generated
     */
    public void setPicurl(String picurl) {
        this.picurl = picurl == null ? null : picurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ShopPic.CreateTime
     *
     * @return the value of ShopPic.CreateTime
     *
     * @mbg.generated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ShopPic.CreateTime
     *
     * @param createtime the value for ShopPic.CreateTime
     *
     * @mbg.generated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ShopPic.IsActive
     *
     * @return the value of ShopPic.IsActive
     *
     * @mbg.generated
     */
    public Short getIsactive() {
        return isactive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ShopPic.IsActive
     *
     * @param isactive the value for ShopPic.IsActive
     *
     * @mbg.generated
     */
    public void setIsactive(Short isactive) {
        this.isactive = isactive;
    }
}