package com.quwb.web.mapper;

import com.quwb.web.entity.BusinessType;

public interface BusinessTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BusinessType
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer businessid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BusinessType
     *
     * @mbg.generated
     */
    int insert(BusinessType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BusinessType
     *
     * @mbg.generated
     */
    int insertSelective(BusinessType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BusinessType
     *
     * @mbg.generated
     */
    BusinessType selectByPrimaryKey(Integer businessid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BusinessType
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(BusinessType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BusinessType
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(BusinessType record);
}