package com.quwb.web.mapper;

import com.quwb.web.entity.Customization;

import java.util.List;

public interface CustomizationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Customization
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Customization
     *
     * @mbg.generated
     */
    int insert(Customization record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Customization
     *
     * @mbg.generated
     */
    int insertSelective(Customization record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Customization
     *
     * @mbg.generated
     */
    Customization selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Customization
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Customization record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Customization
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Customization record);

    /**
     * 根据用户ID获取用户定制信息
     * @param userid
     * @return
     */
   List<Customization> selectByUserId(Integer userid);
}