package com.quwb.web.mapper;

import com.quwb.web.entity.MobileCodeInfo;

public interface MobileCodeInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MobileCodeInfo
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MobileCodeInfo
     *
     * @mbg.generated
     */
    int insert(MobileCodeInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MobileCodeInfo
     *
     * @mbg.generated
     */
    int insertSelective(MobileCodeInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MobileCodeInfo
     *
     * @mbg.generated
     */
    MobileCodeInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MobileCodeInfo
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MobileCodeInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MobileCodeInfo
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MobileCodeInfo record);

    MobileCodeInfo selectByParas(String mobile);
}