package com.quwb.web.mapper;

import com.quwb.web.entity.MsgInfo;

public interface MsgInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MsgInfo
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer msgid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MsgInfo
     *
     * @mbg.generated
     */
    int insert(MsgInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MsgInfo
     *
     * @mbg.generated
     */
    int insertSelective(MsgInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MsgInfo
     *
     * @mbg.generated
     */
    MsgInfo selectByPrimaryKey(Integer msgid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MsgInfo
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MsgInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MsgInfo
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MsgInfo record);
}