package com.quwb.web.mapper;

import com.quwb.web.entity.ShopInfo;

public interface ShopInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ShopInfo
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long shopid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ShopInfo
     *
     * @mbg.generated
     */
    int insert(ShopInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ShopInfo
     *
     * @mbg.generated
     */
    int insertSelective(ShopInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ShopInfo
     *
     * @mbg.generated
     */
    ShopInfo selectByPrimaryKey(Long shopid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ShopInfo
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ShopInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ShopInfo
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ShopInfo record);
}