package com.quwb.web.mapper;

import com.quwb.web.entity.ShopPic;

public interface ShopPicMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ShopPic
     *
     * @mbg.generated
     */
    int insert(ShopPic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ShopPic
     *
     * @mbg.generated
     */
    int insertSelective(ShopPic record);
}