package com.quwb.web.mapper;

import com.quwb.web.entity.UserShopRela;

import java.util.List;

public interface UserShopRelaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UserShopRela
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer relaid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UserShopRela
     *
     * @mbg.generated
     */
    int insert(UserShopRela record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UserShopRela
     *
     * @mbg.generated
     */
    int insertSelective(UserShopRela record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UserShopRela
     *
     * @mbg.generated
     */
    UserShopRela selectByPrimaryKey(Integer relaid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UserShopRela
     *
     * @mbg.generated
     */
    List<UserShopRela> selectByUserId(Integer userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UserShopRela
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(UserShopRela record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UserShopRela
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UserShopRela record);
}